version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  aws-code-deploy: sidlinux22/aws-code-deploy@0.0.1

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  # Create jobs to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-test:
    docker:
      - image: cimg/aws:2023.06
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - aws-code-deploy/get_deployment_id:
          application_name: "change_to_codeDeploy_application_name"
          deployment_group_name: "change_to_codeDeploy_deployment_group_name"
          # Get the latest deployment ID for the specified application and deployment group
      # Add CodeDeploy Steps like copying Artifcate to S3 etc...
      # Fetch new CodeDeploy deployment ID status.
      - aws-code-deploy/get_deployment_status:
          application_name: "change_to_codeDeploy_application_name"
          deployment_group_name: "change_to_codeDeploy_deployment_group_name"
            deployment_start_timeout: "Optional_change_to_codeDeploy_deployment_start_timeout"
            deployment_completion_timeout: "Optional_change_to_codeDeploy_deployment_completion_timeout"
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - command-test:
          filters: *filters
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: sidlinux22/aws-code-deploy
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - command-test
          context: orb-publishing
          filters: *release-filters
