description: >
  This command is to get CodeDeploy latest deployment.
parameters:
  application-name:
    type: string
    description: "The name of the CodeDeploy application."
  deployment-group-name:
    type: string
    description: "The name of the CodeDeploy deployment group."
  pre-deployment-id:
    default: ''
    type: string
    description: "The name of the CodeDeploy deployment group."
steps:
  - run:
      environment:
        APP_NAME: <<parameters.application-name>>
        DEPLOY_GROUP_NAME: <<parameters.deployment-group-name>>
      name: Fetch CodeDeploy <<parameters.deployment-group-name>> deployment group status.
      command: <<include(scripts/get-deployment-status.sh)>>