description: >
  This command is to get CodeDeploy latest deployment.
parameters:
  application-name:
    type: string
    description: "The name of the CodeDeploy application."
  deployment-group-name:
    type: string
    description: "The name of the CodeDeploy deployment group."
  deployment-start-timeout:
    type: integer
    default: 180
    description: "Timeout for deployment start."
  deployment-completion-timeout:
    type: integer
    default: 600
    description: "Timeout for deployment completion."
  pre-deployment-id:
    default: ''
    type: string
    description: "Latest previous deployment ID."
steps:
  - run:
      environment:
        APP_NAME: <<parameters.application-name>>
        DEPLOY_GROUP_NAME: <<parameters.deployment-group-name>>
        DEPLOYMENT_START_TIMEOUT: <<parameters.deployment-start-timeout>>
        DEPLOYMENT_COMPLETION_TIMEOUT: <<parameters.deployment-completion-timeout>>
      name: [CodeDeploy] Fetch <<parameters.deployment-group-name>> deployment status.
      command: <<include(scripts/get-deployment-status.sh)>>