description: >
  A job to get CodeDeploy latest deployment.
parameters:
  application_name:
    type: string
    default: ''
    description: "The name of the CodeDeploy application."
  deployment_group_name:
    type: string
    default: ''
    description: "The name of the CodeDeploy deployment group."
  executor:
    description: The executor to use for this job. By default, this will use the "default" executor provided by this orb.
    type: executor
    default: default
executor: << parameters.executor >>
steps:
  - get_deployment_id:
      application_name: << parameters.application_name >>
      deployment_group_name: << parameters.deployment_group_name>>
