description: >
  A job to get CodeDeploy latest deployment.
parameters:
  application_name:
    type: string
    default: ''
    description: "The name of the CodeDeploy application."
  deployment_group_name:
    type: string
    default: ''
    description: "The name of the CodeDeploy deployment group."
  deployment_start_timeout:
    type: integer
    default: 180
    description: "Timeout for deployment start."
  deployment_completion_timeout:
    type: integer
    default: 600
    description: "Timeout for deployment completion."
  executor:
    description: The executor to use for this job. By default, this will use the "default" executor provided by this orb.
    type: executor
    default: default
executor: << parameters.executor >>
steps:
  - get_deployment_status:
      application_name: << parameters.application_name >>
      deployment_group_name: << parameters.deployment_group_name>>
